### ISSUE TITLE
유기 동물 open API 저장

### ISSUE THREAD

**Issue by newbieJanghan** [mungtage/backend#4]
- [x] open api 데이터 확인
- [x] crontab 작성

**Comment by cyberjam** [comment]
https://github.com/mungtage/pipeline/issues/1

**Comment by cyberjam** [comment]
https://github.com/mungtage/pipeline/issues/3
https://github.com/mungtage/pipeline/issues/5

**Comment by cyberjam** [comment]
- 기존 1000row
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/20448972/196147508-cf08b91c-e4a6-4f64-b745-873ed0490ca8.png">

- processing
<img width="1894" alt="image" src="https://user-images.githubusercontent.com/20448972/196147668-00788451-11f0-4e90-854e-ddbd43d27f72.png">

- test 후 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/20448972/196147564-ead48441-5ba8-4f0f-a56d-1a7893e04ae4.png">


기존 데이터를 초기화 하고 1,074개가 잘 업데이트 되었습니다. 
해당 task 완료 하였습니다.

**Comment by cyberjam** [comment]
https://github.com/mungtage/pipeline/issues/6
