### ISSUE TITLE
이미지 매칭

### ISSUE THREAD

**Issue by newbieJanghan** [mungtage/backend#9]
**table**
- [x] match, match_result table relation

**GET /match?lostId=**
- [x] match 테이블에 새로운 매칭 정보를 생성 (isDone: false)
- [x] 다중 DB 설정
- [x] 비동기로 AI 서버에 이미치 매칭 요청
- [x] 리턴 성공 시 리턴 값을 matchResult 테이블에 matchId와 함께 저장
- [x] matchResult에 저장이 완료되면 update matchId -> (isDone: true)
- [x] (isDone: true)면서 updatedAt이 가장 최근인 match를 leftJoin(matchResults)
- [x] map으로 rescueService.findBy(desertionNo) -> matchResultResponseDto
- [x] 프론트 리턴

**GET /rescue?desertionNo=**
- [x] response data specification
- [x] api 완성

**rescueService**
- [x] matchresult에 담을 값들을 desertionNo로 조회하는 로직

**Comment by cyberjam** [comment]
혹시 AI flask 서버에서 결과를 api서버로 보낼 때 desertionNo기준으로 post하나요?
이미지 저장할때 파일 이름을 desertionNo으로 저장할까해서요.
얼핏 들은것 같은데 확인차 질문 남겨봅니다.

**Comment by newbieJanghan** [comment]
desertionNo가 고유번호일 것으로 가정하고 API 서버에도 그걸 저장하면 어떨까 해서 말씀드렸었습니다.

고유하다면 그렇게 보내주십시오!

**Comment by newbieJanghan** [comment]
> desertionNo가 고유번호일 것으로 가정하고 API 서버에도 그걸 저장하면 어떨까 해서 말씀드렸었습니다.
> 
> 고유하다면 그렇게 보내주십시오!

**Comment by cyberjam** [comment]
2000여개 뽑아서 체크해보니 고유값이네요. desertionNo 기준으로 만들도록 하겠습니다
